os: linux

language: python 

python:
    - "2.7"
    - "3.8"

env:
    - TASK=lint
    - TASK=nosetests

cache:
    apt: true
    directories:
        - $HOME/.cache/pip

addons:
    apt:
        packages:
            - libatlas-dev
            - libblas-dev
            - liblapack-dev
            - gfortran
            - python-numpy
            - python-scipy
            - python3-numpy
            - python3-scipy

before_install:
  - pip install pylint
  - pylint .

install: source scripts/travis_install.sh

script: source scripts/run_tests.sh
